### ISSUE TITLE
im try to compile wireguard in kernal  version 6.2.0.32

### ISSUE THREAD

**Issue by Reshma1206** [runfalk/synology-wireguard#182]
here im try to compile wireguard in kernal version 6.2.0.32 error im facing sk_buff file missing in kernal header 
like this ------->
eg: error: ‘struct sk_buff’ has no member named ‘headers_end’; did you mean ‘headers’?
   85 |                offsetof(struct sk_buff, headers_end) 

but file was inside kernal header  here sk_buff file not fetching while compiling wireguard in kernal .
here im trying to wireguard in kernal version 5.10  its compiling .im not facing any issuse.

here , question is wireguard does compile in kernal version above 6.2.0.32 ?
any can tell the process?
